#!/bin/bash

mkdir build && cd build
cmake .. -G"${{ env.CMAKE_GENERATOR }}" -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DVERSION_SUFIX=${{ env.VERSION_SUFFIX }} -DBUILD_NUMBER=${{ env.BUILD_NUMBER }} -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_PREFIX }} -DOPENSSL_DIR="${{ env.OPENSSL_DIR }}" -DKIMAGEANNOTATOR_DIR=${{ env.INSTALL_PREFIX }}
${MAKE_BINARY}